### ISSUE TITLE
Mount secrets as ENV

### ISSUE THREAD

**Issue by wojcikm** [GoogleCloudPlatform/secrets-store-csi-driver-provider-gcp#127]
Is it possible to mount secrets as env, like [there](https://secrets-store-csi-driver.sigs.k8s.io/topics/set-as-env-var.html) (see examples section)?

**Comment by tam7t** [comment]
Yes! You will have to first sync the secrets to K8s secrets as described:

* https://secrets-store-csi-driver.sigs.k8s.io/topics/sync-as-kubernetes-secret.html
* example [here](https://github.com/GoogleCloudPlatform/secrets-store-csi-driver-provider-gcp/issues/37#issuecomment-678833504)

And then use the K8s sync'd secret as the source for envvar.

**Comment by wojcikm** [comment]
Thanks @tam7t ! I would also suggest to double check, if [those](https://github.com/GoogleCloudPlatform/secrets-store-csi-driver-provider-gcp/issues/37#issuecomment-794346535) steps are done during installation.
