### ISSUE TITLE
When secrets-store-csi-driver for GCP secret manager will be GA ready by GKE?

### ISSUE THREAD

**Issue by shay-berman** [GoogleCloudPlatform/secrets-store-csi-driver-provider-gcp#149]
### Question
1. What is the best practice to integrate secrets from GCP secret manager inside GKE cluster?
2. When GCP secret manager will officially support https://github.com/kubernetes-sigs/secrets-store-csi-driver?   Looks like there is integration but don't know if its GA ready and if its the recommended way https://github.com/GoogleCloudPlatform/secrets-store-csi-driver-provider-gcp.

**Comment by tam7t** [comment]
Thank you for the issue, I have forwarded the feature request to the GKE team for whether this could become a built in add-on.

Both projects have now cut 1.0 releases reflecting the stability of the interface and maturity of the implementation:

* https://github.com/GoogleCloudPlatform/secrets-store-csi-driver-provider-gcp/releases/tag/v1.0.0
* https://github.com/kubernetes-sigs/secrets-store-csi-driver/releases/tag/v1.0.0

A good overview is at https://secrets-store-csi-driver.sigs.k8s.io/#project-status

But yes, currently the driver and the GCP provider must be installed and updated manually. Releases for both are done through Github and I recommend subscribing to get [notifications of new releases](https://github.blog/changelog/2018-11-27-watch-releases/).

With `1.0` there should be no breaking changes (unless/until a `2.x`) and the CHANGELOG is updated to include a summary of changes.

**Comment by dargudear-google** [comment]
It is GA now
https://cloud.google.com/secret-manager/docs/secret-manager-managed-csi-component.md
