### ISSUE TITLE
Compatibility with GKE Autopilot

### ISSUE THREAD

**Issue by karan-kaushik-searce** [GoogleCloudPlatform/secrets-store-csi-driver-provider-gcp#158]

**Comment by tam7t** [comment]
GKE autopilot has a number of limitations that make the CSI driver incompatible from https://cloud.google.com/kubernetes-engine/docs/concepts/autopilot-overview#limits

* Using `hostPath` volumes in write mode is prohibited - this is required for the driver to have access to all pod filesystems for performing mounts
* No privileged Pods - `privileged` is required for the driver to create the `tmpfs` and perform the `mount`

I will forward this request to the GKE team though.

**Comment by karan-kaushik-searce** [comment]
Thank you for clearing it up @tam7t, appreciate it.

Thank you for forwarding the request to the GKE team. Would it be possible to be in the loop for that request?

**Comment by glerchundi** [comment]
Is there something we can do foreigners to push this forward? Is there any way to mount secrets overcoming those limitations? Would love to see progress on this as we're loving GKE Autopilot!

**Comment by raphaelauv** [comment]
is there any news ? thanks

**Comment by glerchundi** [comment]
Hi @tam7t, do you have any news from the GKE team? We'll really appreciate if you can give us some expectations. I don't need that to be in the form of ETAs but it would be enough to know if this is even possible in the short, mid, log-term or never.

Thanks!

**Comment by cah-michael-woodruff** [comment]
I spoke with the GKE platform team at KubeCon and they do have a process to allow you to add the driver to an allow list, but you must open a support case. Also, they are rolling this driver into a managed service very soon but couldnt give me a release date. Q1 is a possibility.

**Comment by dargudear-google** [comment]
It supported in SM-GKE add-on, which is GA.
https://cloud.google.com/secret-manager/docs/secret-manager-managed-csi-component.md
