### ISSUE TITLE
Capability to set file-system permissions for mounted secrets 

### ISSUE THREAD

**Issue by lppartior** [GoogleCloudPlatform/secrets-store-csi-driver-provider-gcp#184]
**Request:**
Capability to set file-system permissions for mounted secrets 

**Describe the solution you'd like**

Supposing my secret is an pem file. Then I'm going to want the file to have permissions 0600.

Looks like everything that this driver mounts gets permissions 0644 - [here](https://github.com/kubernetes-sigs/secrets-store-csi-driver/blob/55efc2dd1a8b64d7f7961d769c79c8100398a555/pkg/secrets-store/nodeserver.go#L48) and [here](https://github.com/kubernetes-sigs/secrets-store-csi-driver/blob/55efc2dd1a8b64d7f7961d769c79c8100398a555/pkg/rotation/reconciler.go#L60) if my grep is good.

I'd like a mechanism to set the permissions to 0600.

**Resources**
Azure provider has the support for per-file permissions
(https://github.com/Azure/secrets-store-csi-driver-provider-azure/blob/24b0767489bbd58b487624878a09f3dec916573d/pkg/server/server.go#L73)

Need similar feature with gcp provider

**Comment by dyolcekaj** [comment]
I had coincidentally opened a PR for this feature a few days before this issue was opened as well 

https://github.com/GoogleCloudPlatform/secrets-store-csi-driver-provider-gcp/pull/182

**Comment by tam7t** [comment]
https://github.com/GoogleCloudPlatform/secrets-store-csi-driver-provider-gcp/releases/tag/v1.2.0 should include this
