### ISSUE TITLE
Can it mount GCP secret in Azure Kubernetes cluster (AKS) using secrets-store-csi-driver

### ISSUE THREAD

**Issue by gpamit** [GoogleCloudPlatform/secrets-store-csi-driver-provider-gcp#186]
### Question
Can it mount GCP secret in Azure Kubernetes cluster (AKS)?

All secrets are defined in GCP using secrets manager. Will like to mount these secrets in Kubernetes cluster running in Azure (AKS)

**Comment by userbradley** [comment]
Why don't you just use the azure secret management? 
https://learn.microsoft.com/en-us/azure/architecture/framework/security/design-storage-keys

As long as those pods can authenticate as a gcp SA, it will work. If azure does not support that, then no

**Comment by gpamit** [comment]
For anyone looking for answer for this, can be done using nodepublishsecretref

https://github.com/GoogleCloudPlatform/secrets-store-csi-driver-provider-gcp/blob/main/docs/authentication.md#nodepublishsecretref

https://github.com/GoogleCloudPlatform/secrets-store-csi-driver-provider-gcp/pull/58
