### ISSUE TITLE
Anthos (GKE on-prem) support?

### ISSUE THREAD

**Issue by esphen** [GoogleCloudPlatform/secrets-store-csi-driver-provider-gcp#201]
### Question
Hi! Does this project support running on Anthos (GKE On-prem)? I tried setting it up but it seems to require fetching metadata from a GCP internal endpoint that does not seem to be present on Anthos.
```
  Warning  FailedMount  12m (x295 over 11h)  kubelet  MountVolume.SetUp failed for volume "gcp-sm-e83a126d0716f731" : rpc error: code = Unknown desc = failed to mount secrets store objects for pod nrl/nrl-api-6d8676b766-xxjb8, err: rpc error: code = PermissionDenied desc = unable to obtain auth for mount: unable to obtain workload identity auth: unable to get project id: Get "http://169.254.169.254/computeMetadata/v1/project/project-id": dial tcp 169.254.169.254:80: i/o timeout
```

**Comment by tam7t** [comment]
There was work to support this done in https://github.com/GoogleCloudPlatform/secrets-store-csi-driver-provider-gcp/pull/190 but a release has not been cut yet that includes that. @amitmodak and I are working on cutting a release here in the next week hopefully and we'll update the bug once thats done.

**Comment by tam7t** [comment]
https://github.com/GoogleCloudPlatform/secrets-store-csi-driver-provider-gcp/releases/tag/v1.2.0 should include this functionality
