### ISSUE TITLE
Set the priorityClassName field of the  CSI  driver daemonset to a critical priority class (system-cluster-critical or system-node-critical). (edi

### ISSUE THREAD

**Issue by sangeethdba** [GoogleCloudPlatform/secrets-store-csi-driver-provider-gcp#204]
### TL;DR

we should consider setting the priorityClassName field of the  CSI Daemonset to a critical priority class (system-cluster-critical or system-node-critical). 

### Design

**Proposal**
this will allow csi driver daemon set is having prioerity over application PODS. we can avoid a situation where Daemonset is unschedulable due to resource limitations and application pods who needs to read secrets will be impacted
**Alternatives considered**

**Resources**

- [Link to documentation](TODO)

**Additional information**

**Comment by tam7t** [comment]
Thank you for the report. I think this was done for the driver in https://github.com/kubernetes-sigs/secrets-store-csi-driver/pull/337  and https://github.com/Azure/secrets-store-csi-driver-provider-azure/pull/263/files for the azure provider - @aramase I wonder if this should be a required thing for _all providers_?

**Comment by marcelocarlos** [comment]
Raised a PR to expose the value while making the change backwards compatible: https://github.com/GoogleCloudPlatform/secrets-store-csi-driver-provider-gcp/pull/303

**Comment by amitmodak** [comment]
Thanks for reporting this issue! There does not seem to be any further action item on this issue and hence we are closing it. Please feel free to reopen this issue or file a new one if you need further assistance.
