### ISSUE TITLE
Monitor Anthos Config Management Test Infrastructure

### ISSUE THREAD

**Issue by colinman** [GoogleCloudPlatform/secrets-store-csi-driver-provider-gcp#36]
Anthos Config Management is used to configure the GCP project for running integration tests. However, we are not currently notified if there are problems with applying changes.

We should set up monitoring/alerting per https://cloud.google.com/anthos-config-management/docs/how-to/monitoring.

**Comment by tam7t** [comment]
I think periodic integration test notifications (tests added in https://github.com/GoogleCloudPlatform/secrets-store-csi-driver-provider-gcp/issues/103) is probably the better way here that would involve fewer moving parts
