### ISSUE TITLE
Failing to pull image "us-docker.pkg.dev/secretmanager-csi/csi-secrets-store-provider-gcp/plugin@sha256:xxxx"

### ISSUE THREAD

**Issue by ropatil010** [GoogleCloudPlatform/secrets-store-csi-driver-provider-gcp#429]
Hi, Failing to pull the image https://github.com/GoogleCloudPlatform/secrets-store-csi-driver-provider-gcp/blob/main/deploy/provider-gcp-plugin.yaml#L86. Can you PTAL? 

Steps tried: 
Trying to install GCP provider from https://github.com/GoogleCloudPlatform/secrets-store-csi-driver-provider-gcp/blob/main/deploy/provider-gcp-plugin.yaml in ns openshift-cluster-csi-drivers and hitting with below mentioned error

oc get ds -n $CSI_DRIVER_INSTALLED_NAMESPACE 
NAME                             DESIRED   CURRENT   READY   UP-TO-DATE   AVAILABLE   NODE SELECTOR            AGE
csi-secrets-store-provider-gcp   3         3         0       3            0           kubernetes.io/os=linux   8m36s

oc get pods -n openshift-cluster-csi-drivers | grep "provider"
csi-secrets-store-provider-gcp-4b7d5                0/1     ImagePullBackOff   0          2m40s
csi-secrets-store-provider-gcp-8nrrq                0/1     ImagePullBackOff   0          2m40s
csi-secrets-store-provider-gcp-b978k                0/1     ImagePullBackOff   0          2m40s

oc describe pod/csi-secrets-store-provider-gcp-4b7d5 -n $CSI_DRIVER_INSTALLED_NAMESPACE
  Normal   Pulling         2m25s (x4 over 3m53s)  kubelet            Pulling image "us-docker.pkg.dev/secretmanager-csi/csi-secrets-store-provider-gcp/plugin@sha256:a493a78bbb4ebce5f5de15acdccc6f4d19486eae9aa4fa529bb60ac112dd6650"
  Warning  Failed          2m24s (x4 over 3m53s)  kubelet            Failed to pull image "us-docker.pkg.dev/secretmanager-csi/csi-secrets-store-provider-gcp/plugin@sha256:a493a78bbb4ebce5f5de15acdccc6f4d19486eae9aa4fa529bb60ac112dd6650": Requesting bearer token: invalid status code from registry 403 (Forbidden)

cc: @jdobson@redhat.com atelang@redhat.com

**Comment by dargudear-google** [comment]
Did you edit the https://github.com/GoogleCloudPlatform/secrets-store-csi-driver-provider-gcp/blob/main/deploy/provider-gcp-plugin.yaml ?
In above file I can see image path is us-docker.pkg.dev/secretmanager-csi/**secrets-store-csi-driver-provider-gcp**/plugin@sha256:a493a78bbb4ebce5f5de15acdccc6f4d19486eae9aa4fa529bb60ac112dd6650 and in the issue description you are getting error for us-docker.pkg.dev/secretmanager-csi/**_csi-secrets-store-provider-gcp_**/plugin@sha256:a493a78bbb4ebce5f5de15acdccc6f4d19486eae9aa4fa529bb60ac112dd6650

Diff:  secrets-store-csi-driver-provider-gcp -> csi-secrets-store-provider-gcp 

can you confirm once that you have not modified the yaml?

**Comment by beginningstories** [comment]
Helloo what is this …? Y ur again sent this type of messages if any doubts
contact directly my cntact below added

Baiju M Ravi
+917559001160

**Comment by ropatil010** [comment]
@dargudear-google Ack, Thanks for inputs.!
