### ISSUE TITLE
reuse GCP API clients

### ISSUE THREAD

**Issue by tam7t** [GoogleCloudPlatform/secrets-store-csi-driver-provider-gcp#94]
The clients:
* `credentials.NewIamCredentialsClient`
* `secretmanager.NewClient`

are created and destroyed on every `Mount` operation. This is because the clients consider the authorization principal to be part of the channel configuration instead of per-rpc configuration.

Creating the clients once on startup will improve performance (reduce rpc latency) since underlying connections can be re-used.

**Comment by christopherL91** [comment]
How can this be done? As far as I see there's an hard dependency on `cfg` which is available upon the `Mount` call. Maybe cache the client using a map.Sync could work?

**Comment by tam7t** [comment]
This will be completed in the next release
